const DEFAULT_IMAGE_WIDTH: number = 300;
const DEFAULT_IMAGE_HEIGHT: number = 300;
const ENTITY_TEAMS: string = 'teams';
const ENTITY_USERS: string = 'users';
const ENTITY_TOURNAMENTS: string = 'tournament';
const DEFAULT_IMAGE_SIZE_LIMIT: number = 5242880;
const ACCEPT_IMAGE_EXTENSION_PATTERN: RegExp = /^(.)?(jpg|jpeg|png|gif|tiff)$/;
const PAGINATION_DEFAULT_LIMIT: number = 10;
const PAGINATION_DEFAULT_PAGE: number = 1;

export default {
  DEFAULT_IMAGE_WIDTH,
  DEFAULT_IMAGE_HEIGHT,
  ENTITY_TEAMS,
  ENTITY_USERS,
  ENTITY_TOURNAMENTS,
  DEFAULT_IMAGE_SIZE_LIMIT,
  ACCEPT_IMAGE_EXTENSION_PATTERN,
  PAGINATION_DEFAULT_LIMIT,
  PAGINATION_DEFAULT_PAGE,
};
